server {
    listen 80;
    server_name admin.store.com;

    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name admin.example.com;

    http2 on;


    include nginx/conf.d/common.conf;

    location ~ \.php$ {
        include nginx/conf.d/fastcgi.conf;
        fastcgi_pass admin_webserver:9000;
    }
}
